### ISSUE TITLE
Get config path automatically

### ISSUE THREAD

**Issue by acidicoala** [g-yui/KoalaGeddon-Configurator#1]
Hey there. You can get the config path without asking user from the windows registry.
Key path: `HKEY_CURRENT_USER\SOFTWARE\acidicoala\Koalageddon`
Value:  `WORKING_DIR`.

**Comment by g-yui** [comment]
I'll add this on the next release, thank you :D

**Comment by acidicoala** [comment]
Just a heads up: The registry key will be changed in the upcoming Koalageddon version.
On 32-bit OS it will be `HKLM\SOFTWARE\acidicoala\Koalageddon`
On 64-bit OS it will be `HKLM\SOFTWARE\WOW6432Node\acidicoala\Koalageddon`

**Comment by g-yui** [comment]
https://github.com/g-yui/KoalaGeddon-Configurator/blob/9e28f056d516d9cf569afec8a1bf60870841f78e/main.py#L3
https://github.com/g-yui/KoalaGeddon-Configurator/blob/9e28f056d516d9cf569afec8a1bf60870841f78e/main.py#L147-L180

Added, I would appreciate if you could give me your feedback before closing this :D

**Comment by acidicoala** [comment]
1. Do not get the working directory by index (L153-154), get it by name instead (`WORKING_DIR`). I might be adding other values in the future and this might affect the index.
2. (Not very critical, but still) Do not concatenate paths manually (L154) . [Example]. Don't be afraid of division operator, it's just overloaded for `Path` class. In general, path building should be left out to the standard library since it will take care of path separators. In general, it is a good practice for cross-platform code.
3. You've really got a phobia of modular files and code, don't you? :)

[Example]: https://github.com/acidicoala/dream-api/blob/2e2a5f52bb06d1dfddb0de94208483b22fe521c5/src/util/resource.py#L10

**Comment by g-yui** [comment]
1.- Fixed
2.- I'll take a look into that later, since I couldn't get it working, for now this will work fine.
3.- How could you tell? ;)
4.- Fixed

https://github.com/g-yui/KoalaGeddon-Configurator/blob/2ece8ab4586e5f6de695c0a41de9e41db00cb9b2/main.py#L146-L171

Any other suggestions?

**Comment by acidicoala** [comment]
```python3
from pathlib import Path # At the top of the file
(working_dir) = winreg.QueryValueEx(access_key, "WORKING_DIR")
config_path = Path(working_dir) /  "Config.jsonc"
return str(config_path) # if u actually need str
```

**Comment by g-yui** [comment]
Implemented, thank you

```
(working_dir) = winreg.QueryValueEx(access_key, "WORKING_DIR")
config_path = pathlib.Path(working_dir[0]) / "Config.jsonc"
return str(config_path)
```
Had to add the index 'cause otherwise it gives me a tuple error ;)

**Comment by acidicoala** [comment]
```python3
(working_dir, _) = QueryValueEx(access_key, "WORKING_DIR")
```

**Comment by g-yui** [comment]
Added for next release, once again, thank you for your help.

https://github.com/g-yui/KoalaGeddon-Configurator/blob/8d43f048ec29b35ec930aa2fd67b0ad3494eb1d2/main.py#L151
https://github.com/g-yui/KoalaGeddon-Configurator/blob/8d43f048ec29b35ec930aa2fd67b0ad3494eb1d2/main.py#L160

**Comment by acidicoala** [comment]
You're welcome!

P.S. You can eliminate the duplicates with a single function:
```python3
def get_config_path(key):
	access_registry = winreg.ConnectRegistry(None, key)
	access_key = winreg.OpenKey(access_registry, r"SOFTWARE\acidicoala\Koalageddon")
	(working_dir, _) = winreg.QueryValueEx(access_key, "WORKING_DIR")
	config_path = pathlib.Path(working_dir) / "Config.jsonc"
	return str(config_path)

# Usage:

try:
	print(get_config_path(winreg.HKEY_LOCAL_MACHINE))
except FileNotFoundError:
	try:
		print(get_config_path(winreg.HKEY_CURRENT_USER))
	except FileNotFoundError:
		# Koalageddon not installed
		pass
```

**Comment by acidicoala** [comment]
P.S.S. I see you begin to make use of classes, which is good. But you declare every function as `staticmethod`, thus defeating the purpose of classes. You are better off just having them as global functions in their own file, if they really need to be static.

**Comment by g-yui** [comment]
I'll change it later, among other things ;)
Lots of 'em do need to be static, I did it  more as a way of organization than anything else, though I will have that in mind for later projects!
