### ISSUE TITLE
Bundle the logos

### ISSUE THREAD

**Issue by acidicoala** [g-yui/KoalaGeddon-Configurator#2]
Hey there. I've noticed you have a portable build. But yet you still include the logos separately. With PyInstaller you can bundle the logos into the executable as well.

**Comment by g-yui** [comment]
I've tried but thus far I have not managed to make it work, it launches a "Failed to execute main" error, even with this line of code
```
def resource_path(#path to logos#):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
```

**Comment by acidicoala** [comment]
Maybe this can help:
https://github.com/acidicoala/dream-api/blob/2e2a5f52bb06d1dfddb0de94208483b22fe521c5/src/util/resource.py#L7

This implementation is specific to dream api directory structure. You will need to make appropriate adjustments with respect to your project.

**Comment by g-yui** [comment]
Fixed! It was quite easy too once I understood what that line was doing, I need to learn a lot more 😄 
https://github.com/g-yui/KoalaGeddon-Configurator/blob/2ece8ab4586e5f6de695c0a41de9e41db00cb9b2/main.py#L136-L143
